### ISSUE TITLE
I got this error after install and execute

### ISSUE THREAD

**Issue by pradeepnew** [remoteinterview/compilebox#14]
POST http://127.0.0.1/compile

404 Not Found

**Comment by pradeepnew** [comment]
I have installed this but nothing happen.
I got beloe error in firebug
POST http://127.0.0.1/compile

404 Not Found

**Comment by pradeepnew** [comment]
I have execute the below command
docker info

Output:
Containers: 2
Images: 26
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 30
Execution Driver: native-0.2
Kernel Version: 3.16.0-45-generic
WARNING: No swap limit support

**Comment by pradeepnew** [comment]
Is docker is install successfully or not

**Comment by pradeepnew** [comment]
Its giving error
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by pradeepnew** [comment]
sudo nodsjs app.js
Listening at 80

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at HTTPServer.Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at HTTPServer.Server.listen (net.js:1135:5)
    at Object.<anonymous> (/var/www/compilebox/API/app.js:74:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by khandaa** [comment]
Please add compile file in the package.

**Comment by anistark** [comment]
@pradeepnew Change port from 80 to 8000 or 8080 and it'll run..
