### ISSUE TITLE
app.js is dead when trying to run following in python

### ISSUE THREAD

**Issue by varnar** [remoteinterview/compilebox#55]
```
flag = 1
while (flag): 
    print  ('Given flag is really true!')
print "Done"

```

And error:

ATTEMPTING TO REMOVE: temp/2fe6cc4c7772de1a7581
------------------------------
buffer.js:385
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:385:11)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:378:21)

**Comment by varnar** [comment]
but this is working

```
flag = 1
while (flag): 
   print ('Given flag is really true!')
   flag = 0
```
