### ISSUE TITLE
run app.js failed

### ISSUE THREAD

**Issue by twz915** [remoteinterview/compilebox#8]
Listening at 80
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at HTTPServer.Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at HTTPServer.Server.listen (net.js:1240:5)
    at Object.<anonymous> (/home/qnhu/Downloads/compilebox/API/app.js:74:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by asadm** [comment]
Try running with admin right. (sudo node app.js). 
This is required since you are trying to use port 80.
